location_name = "eastus2"
resource_group_name = "rg-shorturl2"
storage_account_name = "stazfuncshorturl2"
plan_name = "plan-azfuncshorturl2"
app_insights_name = "appis-azfuncshorturl2"
func_name = "azfunc-shorturl2"
keyvault_name = "kv-shorturl2"
cosmos_name = "cosmos-shorturl2"
event_hub_namespace = "evhns-shorturl2"
event_hub_name = "evh-shorturl2"
cosmosPrimaryKeyEmulator = "C2y6yDjf5/R+ob0N8A7Cgv30VRDJIWEHLM+4QDU5DE2nQ9nDuVTqobD4b8mGGyPMbIZnqyMsEcaGQy67XIw/Jw=="
cosmosConfigTemplateEmulator = "ewoJInVzZUNvc21vcyI6IHRydWUsCgkidXJpIjogImh0dHBzOi8vbG9jYWxob3N0OjgwODEiLAoJInByaW1hcnlLZXkiOiAie3twcmltYXJ5S2V5fX0iLAoJInByaW1hcnlDb25uZWN0aW9uU3RyaW5nIjogIkFjY291bnRFbmRwb2ludD1odHRwczovL2xvY2FsaG9zdDo4MDgxLztBY2NvdW50S2V5PXt7cHJpbWFyeUtleX19IiwKCSJpZGVudGl0eVNlcnZlck9wZXJhdGlvbmFsU3RvcmUiOiB7CgkJImRhdGFiYXNlIjogImRiLXNob3J0VXJsIiwKCQkiY29sbGVjdGlvbiI6ICJvcGVyYXRpb25hbCIKCX0KfQ=="
cosmosConfigTemplateProduction = "ewoJInVzZUNvc21vcyI6IHRydWUsCgkidXJpIjogImh0dHBzOi8vY29zbW9zLXNob3J0dXJsMi5kb2N1bWVudHMuYXp1cmUuY29tOjQ0MyIsCgkicHJpbWFyeUtleSI6ICJ7e3ByaW1hcnlLZXl9fSIsCgkicHJpbWFyeUNvbm5lY3Rpb25TdHJpbmciOiAiQWNjb3VudEVuZHBvaW50PWh0dHBzOi8vY29zbW9zLXNob3J0dXJsMi5kb2N1bWVudHMuYXp1cmUuY29tOjQ0My87QWNjb3VudEtleT17e3ByaW1hcnlLZXl9fSIsCgkiT3BlcmF0aW9uYWxTdG9yZSI6IHsKCQkiZGF0YWJhc2UiOiAiZGItc2hvcnRVcmwiLAoJCSJjb2xsZWN0aW9uIjogIm9wZXJhdGlvbmFsIgoJfQp9"
azFuncShorturlClientCredentials = "ewoJImF1dGhvcml0eSI6ICJodHRwczovL2FwaW0tZmx1ZmZ5b2F1dGgyLmF6dXJlLWFwaS5uZXQvb2F1dGgyIiwKCSJ0ZW5hbnRzIjogW3sKCQkiY3JlZGVudGlhbHMiOiB7CgkJCSJjbGllbnRfaWQiOiAiYjJiLWNsaWVudCIsCgkJCSJjbGllbnRfc2VjcmV0IjogInNlY3JldCIKCQl9LAoJCSJuYW1lIjogIm1hcmtldGluZyIsCgkJIm9wdGlvbnMiOiB7CgkJCSJtYXhfdHRsIjogMjU5MjAwMAoJCX0KCX1dCn0="
jwtValidateSettings = "ewoJImF1dGhvcml0eSI6ICJodHRwczovL2FwaW0tZmx1ZmZ5b2F1dGgyLmF6dXJlLWFwaS5uZXQvb2F1dGgyIiwKCSJvcHRpb25zIjogewoJCSJhdWRpZW5jZSI6IHsKCQkJInJlcXVpcmVkIjogdHJ1ZSwKCQkJInZhbGlkQXVkaWVuY2VzIjogWyJ1cmwtc2hvcnRlbmVyIl0KCQl9LAoJCSJpc3N1ZXIiOiB7CgkJCSJyZXF1aXJlZCI6IHRydWUsCgkJCSJ2YWxpZElzc3VlciI6ICJodHRwczovL2FwaW0tZmx1ZmZ5b2F1dGgyLmF6dXJlLWFwaS5uZXQvb2F1dGgyIiwKCQkJIlZhbGlkYXRlSXNzdWVyU2lnbmluZ0tleSI6IGZhbHNlCgkJfSwKCQkibGlmZXRpbWUiOiB7CgkJCSJyZXF1aXJlZCI6IHRydWUsCgkJCSJjbG9ja1NrZXctbWluIjogNQoJCX0sCgkJInNpZ25lZFRva2VuIjogewoJCQkicmVxdWlyZWQiOiB0cnVlCgkJfQoJfQp9"

# export ARM_ACCESS_KEY=$(az keyvault secret show --name terraform-backend-key --vault-name kv-tf-shorturl2 --query value -o tsv)

